# Generated by Django 5.2.3 on 2025-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_contactsubmission_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='submitted_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
