# Generated by Django 5.2.4 on 2025-07-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0003_rename_submitted_at_contactsubmission_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=255)),
                ('consultancy_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='advocates.consultancyservice')),
            ],
        ),
    ]
