# Generated by Django 5.2.3 on 2025-07-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0004_consultancyservice_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome class, e.g., "fas fa-balance-scale"', max_length=100)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ServiceDetail',
            new_name='ConsultancyDetail',
        ),
        migrations.CreateModel(
            name='CorporateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=255)),
                ('corporate_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='advocates.corporateservice')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=255)),
                ('dispute_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='advocates.disputeservice')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=255)),
                ('property_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='advocates.propertyservice')),
            ],
        ),
    ]
