# Generated by Django 5.2.3 on 2025-07-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0005_corporateservice_disputeservice_propertyservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancyservice',
            options={'verbose_name': 'Consultancy Service', 'verbose_name_plural': 'Consultancy Services'},
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='corporateservice',
            options={'verbose_name': 'Corporate Service', 'verbose_name_plural': 'Corporate Services'},
        ),
        migrations.AlterModelOptions(
            name='disputeservice',
            options={'verbose_name': 'Dispute Resolution Service', 'verbose_name_plural': 'Dispute Resolution Services'},
        ),
        migrations.AlterModelOptions(
            name='propertyservice',
            options={'verbose_name': 'Property Law Service', 'verbose_name_plural': 'Property Law Services'},
        ),
        migrations.AddField(
            model_name='consultancyservice',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional meta description for SEO.', max_length=160),
        ),
        migrations.AddField(
            model_name='consultancyservice',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title (overrides default).', max_length=60),
        ),
        migrations.AddField(
            model_name='corporateservice',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional meta description for SEO.', max_length=160),
        ),
        migrations.AddField(
            model_name='corporateservice',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title (overrides default).', max_length=60),
        ),
        migrations.AddField(
            model_name='disputeservice',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional meta description for SEO.', max_length=160),
        ),
        migrations.AddField(
            model_name='disputeservice',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title (overrides default).', max_length=60),
        ),
        migrations.AddField(
            model_name='propertyservice',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional meta description for SEO.', max_length=160),
        ),
        migrations.AddField(
            model_name='propertyservice',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title (overrides default).', max_length=60),
        ),
        migrations.AlterField(
            model_name='consultancyservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g., "fas fa-scale-balanced"', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultancyservice',
            name='summary',
            field=models.TextField(help_text='Short description for SEO and previews.'),
        ),
        migrations.AlterField(
            model_name='corporateservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g., "fas fa-scale-balanced"', max_length=100),
        ),
        migrations.AlterField(
            model_name='corporateservice',
            name='summary',
            field=models.TextField(help_text='Short description for SEO and previews.'),
        ),
        migrations.AlterField(
            model_name='disputeservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g., "fas fa-scale-balanced"', max_length=100),
        ),
        migrations.AlterField(
            model_name='disputeservice',
            name='summary',
            field=models.TextField(help_text='Short description for SEO and previews.'),
        ),
        migrations.AlterField(
            model_name='disputeservice',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g., "fas fa-scale-balanced"', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyservice',
            name='summary',
            field=models.TextField(help_text='Short description for SEO and previews.'),
        ),
        migrations.AlterField(
            model_name='propertyservice',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
