# Generated by Django 5.2.6 on 2025-09-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0006_alter_consultancyservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='consultancydetail',
            name='consultancy_service',
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.RemoveField(
            model_name='corporatedetail',
            name='corporate_service',
        ),
        migrations.RemoveField(
            model_name='disputedetail',
            name='dispute_service',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='property_service',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='advocates.category'),
        ),
        migrations.DeleteModel(
            name='ConsultancyDetail',
        ),
        migrations.DeleteModel(
            name='ConsultancyService',
        ),
        migrations.DeleteModel(
            name='CorporateDetail',
        ),
        migrations.DeleteModel(
            name='CorporateService',
        ),
        migrations.DeleteModel(
            name='DisputeDetail',
        ),
        migrations.DeleteModel(
            name='DisputeService',
        ),
        migrations.DeleteModel(
            name='PropertyDetail',
        ),
        migrations.DeleteModel(
            name='PropertyService',
        ),
    ]
