# Generated by Django 5.2.6 on 2025-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0007_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('consultancy', 'Consultancy Services'), ('dispute', 'Dispute Resolution'), ('corporate', 'Corporate & Commercial Law'), ('intellectual', 'Intellectual Property')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('consultancy', 'Consultancy Services'), ('dispute', 'Dispute Resolution'), ('corporate', 'Corporate & Commercial Law'), ('intellectual', 'Intellectual Property')], max_length=50)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
