# Generated by Django 5.2.6 on 2025-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0009_alter_scheduledcall_options_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_red_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledcall',
            name='is_red_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledcall',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
