# Generated by Django 5.2.6 on 2025-09-24 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0010_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminactivitylog',
            old_name='user',
            new_name='admin_user',
        ),
        migrations.RenameField(
            model_name='adminactivitylog',
            old_name='login_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='action',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
