# Generated by Django 5.2.6 on 2025-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0011_rename_user_adminactivitylog_admin_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminactivitylog',
            old_name='created_at',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='adminactivitylog',
            old_name='admin_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
