# Generated by Django 5.2.6 on 2025-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0013_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('commercial', 'Commercial Practice'), ('dispute', 'Dispute Resolution'), ('debt', 'Debt Recovery'), ('intellectual', 'Intellectual Property'), ('real_estate', 'Real Estate Law'), ('support', 'Support Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('commercial', 'Commercial Practice'), ('dispute', 'Dispute Resolution'), ('debt', 'Debt Recovery'), ('intellectual', 'Intellectual Property'), ('real_estate', 'Real Estate Law'), ('support', 'Support Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='subject',
            field=models.CharField(choices=[('commercial', 'Commercial Practice'), ('dispute', 'Dispute Resolution'), ('debt', 'Debt Recovery'), ('intellectual', 'Intellectual Property'), ('real_estate', 'Real Estate Law'), ('support', 'Support Services')], max_length=50),
        ),
    ]
