# Generated by Django 5.2.6 on 2025-09-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0016_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcall',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advocates.calendarevent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='advocates.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='time_slot',
            field=models.TimeField(),
        ),
    ]
