# Generated by Django 5.2.6 on 2025-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0018_client_remove_scheduledcall_calendar_event_call_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Message'), ('call', 'Call')], max_length=20)),
                ('client', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('red_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
