# Generated by Django 5.2.7 on 2025-10-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('extra_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('commercial', 'Commercial Practice'), ('dispute', 'Dispute Resolution'), ('consultancy', 'Consultancy Services'), ('debt', 'Debt Recovery'), ('intellectual', 'Intellectual Property'), ('real_estate', 'Real Estate Law'), ('support', 'Support Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='subject',
            field=models.CharField(choices=[('commercial', 'Commercial Practice'), ('dispute', 'Dispute Resolution'), ('consultancy', 'Consultancy Services'), ('debt', 'Debt Recovery'), ('intellectual', 'Intellectual Property'), ('real_estate', 'Real Estate Law'), ('support', 'Support Services')], max_length=50),
        ),
    ]
