# Generated by Django 5.2.6 on 2025-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0020_teammember_alter_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('other', 'Other')], max_length=20)),
                ('comments', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
