# Generated by Django 5.2.6 on 2025-10-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0023_categories_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='advocates.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('publication', 'Publication'), ('article', 'Article'), ('news', 'News'), ('quote', 'Quote')], default='publication', max_length=20),
        ),
    ]
